name: rt_yaml
version: 0.1.0
description: A library for YAML roundtripping with format and comment preservation.
homepage: https://bitbeast18.github.io/rt_yaml
repository: https://github.com/bitbeast18/rt_yaml
issue_tracker: https://github.com/bitbeast18/rt_yaml/issues
documentation: https://bitbeast18.github.io/rt_yaml

dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.14.3

environment:
  